package frontends

import (
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/netip"

	"github.com/UselessMnemonic/proxygw/pkg/config"
	"github.com/UselessMnemonic/proxygw/pkg/frontend"
)

const serverReadBufferSize = 2048

const (
	steamNetworkingUDPChallengeRequest = 32
	steamNetworkingUDPConnectRequest   = 34
	steamNetworkingUDPMinPacketSize    = 6
)

// ServerHandler listens on Valheim's gameplay port and wakes the target when a
// player tries to connect.
type ServerHandler struct {
	address netip.AddrPort
	warm    chan struct{}
	logger  *slog.Logger

	conn   *net.UDPConn
	done   chan error
	closed bool
}

// Start opens the UDP gameplay listener.
func (s *ServerHandler) Start() error {
	if s.closed {
		return fmt.Errorf("valheim server frontend is closed")
	}
	if s.conn != nil {
		s.logger.Info("valheim server frontend already started", "listen", s.address.String())
		return nil
	}

	s.logger.Info("starting valheim server frontend", "listen", s.address.String())
	conn, err := net.ListenUDP("udp", net.UDPAddrFromAddrPort(s.address))
	if err != nil {
		s.logger.Error("valheim server frontend listen failed", "listen", s.address.String(), "err", err)
		return err
	}

	s.conn = conn
	s.done = make(chan error, 1)
	go func() {
		s.done <- s.serve(conn)
	}()

	s.logger.Info("valheim server frontend started", "listen", s.address.String())
	return nil
}

// Stop closes the UDP gameplay listener.
func (s *ServerHandler) Stop() error {
	if s.conn == nil {
		s.logger.Info("valheim server frontend already stopped")
		return nil
	}

	s.logger.Info("stopping valheim server frontend")
	err := s.conn.Close()
	s.conn = nil

	serveErr := <-s.done
	s.done = nil
	err = errors.Join(err, serveErr)
	if err != nil {
		s.logger.Info("valheim server frontend stopped with error", "err", err)
		return err
	}

	s.logger.Info("valheim server frontend stopped")
	return nil
}

// Close permanently stops the gameplay listener.
func (s *ServerHandler) Close() error {
	if s.closed {
		return nil
	}
	s.closed = true
	return s.Stop()
}

// ShouldWarm returns warm signals generated by player traffic.
func (s *ServerHandler) ShouldWarm() <-chan struct{} {
	return s.warm
}

func (s *ServerHandler) serve(conn *net.UDPConn) error {
	buf := make([]byte, serverReadBufferSize)
	for {
		n, addr, err := conn.ReadFromUDPAddrPort(buf)
		if err != nil {
			if errors.Is(err, net.ErrClosed) {
				return nil
			}
			return err
		}

		if !looksLikeValheimGameplay(buf[:n]) {
			s.logger.Debug("non-valheim gameplay packet ignored", "remote", addr.String(), "bytes", n)
			continue
		}

		s.logger.Debug("valheim gameplay packet received", "remote", addr.String(), "bytes", n, "warm_queued", s.tickWarm())
	}
}

func looksLikeValheimGameplay(packet []byte) bool {
	if len(packet) < steamNetworkingUDPMinPacketSize {
		return false
	}

	switch packet[0] {
	case steamNetworkingUDPChallengeRequest, steamNetworkingUDPConnectRequest:
		return true
	default:
		return false
	}
}

func (s *ServerHandler) tickWarm() bool {
	select {
	case s.warm <- struct{}{}:
		return true
	default:
		return false
	}
}

// NewServerHandler creates a Valheim gameplay frontend. Valheim client traffic
// is UDP and should wake the target; Steam/A2S query traffic should use the
// separate status frontend so server-list polling does not wake the server.
func NewServerHandler(name string, protocol config.Protocol, address netip.AddrPort, _ map[string]any) (frontend.Handler, error) {
	if protocol != config.ProtocolUDP {
		return nil, fmt.Errorf("valheim server frontend requires udp protocol")
	}

	return &ServerHandler{
		address: address,
		warm:    make(chan struct{}, 1),
		logger:  slog.Default().With("handler", "server", "frontend", name),
	}, nil
}
